services:
  postgres:
    container_name: nest-clean-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password_pg
      POSTGRES_DB: praticas_nest
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres